export interface ProductUpdate {
  id: string
  version: string
  date: string
  title: string
  summary: string
  highlights: string[]
  category: 'dashboard' | 'theme' | 'insight' | 'workflow'
}

export const productUpdates: ProductUpdate[] = [
  {
    id: '2026-04-26-token-cost-tooltip',
    version: 'v3.3.0',
    date: '2026-04-26',
    title: '토큰 비용 툴팁 + 캐시 요금 계산 수정',
    summary: '세션·메시지 토큰 뱃지에 마우스를 올리면 정확한 수치와 API 예상 비용이 표시돼요. 캐시 쓰기 요금 계산 오류도 수정됐어요.',
    highlights: [
      '세션 헤더 토큰 뱃지: hover 시 입력/출력/캐시 breakdown + 예상 비용',
      '메시지 토큰 뱃지: hover 시 정확한 수치(쉼표 형식) + 예상 비용',
      'cache_creation 토큰 요금 수정 ($0.30 → $3.75/M for Sonnet)',
      'claude-haiku-3.5/4+ 별도 요금 적용 ($0.80 input / $4 output)',
      '토큰 비용 툴팁 레이어 클리핑 버그 수정',
    ],
    category: 'dashboard',
  },
  {
    id: '2026-04-22-role-scoring-v3',
    version: 'v3.2.0',
    date: '2026-04-22',
    title: 'AI 역할 정확도 재설계 & 토큰 배지 정리',
    summary: 'AI가 수행한 역할을 더 정확하게 판별하도록 스코어링 로직을 재설계했어요. 히스토리·세션 뷰의 토큰 배지도 한 가지 스타일로 통일됐어요.',
    highlights: ['AI 역할 스코어링 Phase 1~3 재설계 (구조적 시그널·혼합 역할·신뢰도 지표)', '역할 시그널 어휘를 실전 사용 패턴 기반으로 재조정', '토큰 배지 UI 통일 (히스토리 / 세션 헤더 / 메시지)', '유저 메시지에도 토큰 수 표시 (초록 배지)', '메시지에 섞이던 <image> 태그 자동 정리', 'memtest 스킬 + AI 역할 평가 자동화 도입'],
    category: 'insight',
  },
  {
    id: '2026-04-20-session-replay',
    version: 'v3.1.4',
    date: '2026-04-20',
    title: '세션 리플레이 & AI 직업 라벨 리브랜딩',
    summary: '세션을 타임라인 스크러버로 되감기·재생할 수 있어요. AI 직업 카테고리 라벨도 더 친근한 표현으로 정돈됐어요.',
    highlights: ['세션 리플레이 프로토타입 (타임라인 스크러버)', 'AI 직업 카테고리 라벨 재정돈', '새소식 v3.0.1~v3.1.1 누락 내역 보강'],
    category: 'workflow',
  },
  {
    id: '2026-04-20-session-view-ux',
    version: 'v3.1.2',
    date: '2026-04-20',
    title: 'HTML 단일 파일 기본 모드 & 세션 뷰 개선',
    summary: 'npx memradar@latest 하나로 단일 HTML 파일이 생성돼 바로 열려요. 세션 뷰는 마크다운 렌더링과 말풍선 레이아웃으로 개선됐어요.',
    highlights: ['HTML 파일 생성이 기본 모드로 변경 (서버 불필요)', '세션 대화 마크다운 렌더링 지원', '배지 색상 테마별 자동 적용', 'npx 실행 시 구버전이면 자동으로 최신 버전 재실행'],
    category: 'workflow',
  },
  {
    id: '2026-04-19-npx-auto-reexec',
    version: 'v3.1.1',
    date: '2026-04-19',
    title: 'npx 실행 시 신버전 자동 재실행',
    summary: 'npx memradar@latest 실행 시 구버전이 캐시돼 있어도 최신 버전을 자동으로 감지해 바로 재실행돼요.',
    highlights: ['구버전 캐시 감지 후 최신 버전으로 자동 재실행', '업데이트 확인 없이 항상 최신 버전 실행 보장'],
    category: 'workflow',
  },
  {
    id: '2026-04-19-session-view-markdown',
    version: 'v3.1.0',
    date: '2026-04-19',
    title: '세션 뷰 마크다운 렌더링 & 배지 개선',
    summary: '세션 대화 내용이 마크다운으로 렌더링되고, 모델 배지 색상이 라이트/다크 테마에 따라 자동으로 조정돼요.',
    highlights: ['세션 메시지 마크다운 렌더링 (코드 블록, 표, 링크 등)', '모델 배지 색상 테마 인식형으로 변경 (에메랄드 그린)', '상단 버튼 레이아웃 서브타이틀 기준선 정렬'],
    category: 'dashboard',
  },
  {
    id: '2026-04-18-auto-update-spawn',
    version: 'v3.0.3',
    date: '2026-04-18',
    title: '업데이트 알림 정렬 수정',
    summary: '터미널에서 업데이트 알림 텍스트 정렬이 깨지던 문제를 수정했어요.',
    highlights: ['업데이트 안내 문구 정렬 오류 수정', 'CLI 출력 가독성 개선'],
    category: 'workflow',
  },
  {
    id: '2026-04-18-auto-update-prompt',
    version: 'v3.0.2',
    date: '2026-04-18',
    title: '자동 업데이트 설치 프롬프트',
    summary: '새 버전이 있을 때 확인하면 자동으로 최신 버전을 설치하고 재실행해요.',
    highlights: ['업데이트 확인 시 자동 설치 및 재실행', '사용자 확인 후 npx --yes로 최신 버전 실행'],
    category: 'workflow',
  },
  {
    id: '2026-04-18-update-notifier',
    version: 'v3.0.1',
    date: '2026-04-18',
    title: '업데이트 알림 기능',
    summary: '실행 시 새 버전이 배포돼 있으면 터미널에 업데이트 안내가 표시돼요.',
    highlights: ['npm 레지스트리에서 최신 버전 자동 확인', '새 버전 있을 때 업데이트 안내 출력'],
    category: 'workflow',
  },
  {
    id: '2026-04-18-session-donut',
    version: 'v3.0.0',
    date: '2026-04-18',
    title: '세션 길이 도넛 & 스킬 도넛 차트',
    summary: '세션 길이 분포와 자주 사용한 스킬(도구)을 도넛 차트로 한눈에 볼 수 있어요.',
    highlights: ['세션 길이 도넛 차트 추가 (Quick/Standard/Deep)', '스킬 사용 도넛 차트 추가', '탑바 레이아웃 위치 조정'],
    category: 'dashboard',
  },
  {
    id: '2026-04-18-personality-redesign',
    version: 'v0.2.12',
    date: '2026-04-18',
    title: '코딩 성격 유형 시스템 재설계',
    summary: 'AI 도구 사용량이 아닌 사용자의 실제 행동 패턴(메시지 스타일, 프로젝트 집중도, 세션 리듬)으로 성격 유형을 판별해요.',
    highlights: ['설계자/탐험가, 한우물/유목민, 마라토너/스프린터 3축', 'AI 직업 카테고리 통합 및 "내 AI의 직업" 리브랜딩', '세션 종류(Quick/Standard/Deep) 기반 리듬 분석'],
    category: 'insight',
  },
  {
    id: '2026-04-17-server-mode',
    version: 'v0.2.2',
    date: '2026-04-17',
    title: '로컬 서버 모드 전환',
    summary: 'npx memradar가 이제 로컬 서버를 띄워 앱을 즉시 로드해요. 18 MB HTML 대신 0.6 MB 앱이 바로 열리고, 세션은 백그라운드로 스트리밍돼요.',
    highlights: ['localhost:3939 서버 자동 기동', '세션 10개씩 점진 로딩', '기존 HTML 모드는 --static 플래그로 유지'],
    category: 'workflow',
  },
  {
    id: '2026-04-17-codex-support',
    version: 'v0.2.0',
    date: '2026-04-17',
    title: 'Codex 세션 지원',
    summary: 'Claude 세션과 함께 Codex 세션 로그도 자동으로 스캔하고 분석해요. 토큰 가격 계산과 테마 정책도 추가됐어요.',
    highlights: ['~/.codex/sessions/ 자동 스캔', '토큰 비용 계산 라이브러리', '테마 정책 모듈 추가'],
    category: 'insight',
  },
  {
    id: '2026-04-15-dashboard-polish',
    version: 'v0.1.4',
    date: '2026-04-15',
    title: '대시보드 폴리시',
    summary: '히트맵 비율, 카드 정렬, 툴팁 레이어를 다듬어 메인 화면이 더 안정적으로 보이게 정리했어요.',
    highlights: ['활동 히트맵 레이아웃 재정렬', '툴팁과 팝오버 레이어 정리', '세션 지표 카드 정렬 보정'],
    category: 'dashboard',
  },
  {
    id: '2026-04-15-theme-refresh',
    version: 'v0.1.3',
    date: '2026-04-15',
    title: '테마 선택 개선',
    summary: '시스템 다크/라이트 기본값을 따르도록 정리하고, 모드와 포인트 색을 다시 고르기 쉽게 바꿨어요.',
    highlights: ['시스템 테마 기본 연동', '포인트 색 선택 흐름 정리', '뒤로 가기 가능한 테마 패널'],
    category: 'theme',
  },
  {
    id: '2026-04-14-insight-updates',
    version: 'v0.1.2',
    date: '2026-04-14',
    title: '인사이트 상호작용 강화',
    summary: '시간대 그래프, 워드클라우드, 모델 그래프에서 hover 정보가 더 자연스럽게 보이도록 손봤어요.',
    highlights: ['시간대 툴팁 개선', '워드클라우드 hover 정보 추가', '모델 도넛 차트 오버레이 정리'],
    category: 'insight',
  },
  {
    id: '2026-04-13-workflow-release',
    version: 'v0.1.1',
    date: '2026-04-13',
    title: '탐색 플로우 확장',
    summary: '세션 검색, Code Report, 로컬 로그 자동 불러오기까지 연결해 첫 사용 흐름을 매끄럽게 만들었어요.',
    highlights: ['세션 검색 뷰 추가', 'Code Report 경험 확장', '로컬 로그 자동 로드'],
    category: 'workflow',
  },
]

export const latestProductUpdate = productUpdates[0]
