export interface ProductUpdate {
  id: string
  version: string
  date: string
  title: string
  summary: string
  highlights: string[]
  category: 'dashboard' | 'theme' | 'insight' | 'workflow'
}

export const productUpdates: ProductUpdate[] = [
  {
    id: '2026-08-03-model-attribution-per-response',
    version: 'v4.2.0',
    date: '2026-08-03',
    title: '모델 통계 정확도 대수술 — 대화마다, 응답마다 "무슨 모델이었는지"',
    summary:
      '한 대화 안에서도 모델이 바뀔 수 있는데(실측: 대화의 42%가 혼합), 지금까지는 처음 만난 모델 하나로 대화 전체를 라벨링해 통계 절반이 어긋나 있었어요. 이제 AI가 실제로 답한 응답 단위로 정확히 집계하고, 각 응답 옆에 모델 필을 상시 표시합니다. "이 질문은 무슨 모델이 답했지?"가 hover 없이 바로 보여요.',
    highlights: [
      '대화 목록·상세 헤더에 모델 구성 배지 — "Opus 4.8 · Opus 5"처럼 쓴 모델 전부 표시, hover 시 모델별 응답 수·비중',
      '각 AI 응답 옆에 모델 필 상시 표시 — 대화 중간에 바뀐 지점도 응답 단위로 정확히',
      '모델이 바뀐 이유도 표시 — "사용량 한도" 같은 정규화된 분류로 (원문의 시간대 정보는 내보내기에 싣지 않음)',
      '"사용한 모델" 도넛·Wrapped 모델 슬라이드가 응답 수 기준으로 — 세션당 1표의 왜곡 제거',
      '대시보드 소스 필터가 모델 도넛에도 적용 — Claude로 거르면 gpt가 사라집니다',
      '중단·한도초과 시스템 응답(<synthetic>)이 모델 통계·배지에 섞이던 오염 제거',
      '검색 모델 필터 수정 — 그 모델이 답한 적 없는 내 프롬프트가 결과에 나오던 버그',
      'Claude 5 계열 모델명 표기 정리 — claude-fable-5 → "Fable 5"',
    ],
    category: 'insight',
  },
  {
    id: '2026-07-05-empty-session-title-tooltip-personality-cta',
    version: 'v4.1.0',
    date: '2026-07-05',
    title: '스킬 세션 제목 복원 + 테마 툴팁 레이어 수정 + 성향 진단 바로가기',
    summary: '스킬(/goal, /autogoal 등)로 시작한 대화가 대시보드에서 "(빈 세션)"으로 뜨던 문제를 고쳤어요. 이제 실제로 입력한 요청이 제목으로 보입니다. 테마 변경 버튼 툴팁이 아래 카드에 가려지던 레이어 문제도 정리했고, Wrapped 마지막 화면에서 몇 가지 질문으로 내 성향을 진단할 수 있는 버튼을 추가했어요.',
    highlights: [
      '스킬(/goal 등)로 시작한 세션 제목 복원 — "(빈 세션)" 대신 실제 입력한 요청을 제목으로 표시',
      '제목뿐 아니라 대화 검색·내보내기·리플레이도 스킬 세션에서 함께 정상화',
      '테마 변경 툴팁이 아래 카드에 가려지던 레이어(z-index) 문제 수정 — 상단바 스택 컨텍스트 정리',
      'Wrapped 마지막 화면에 "정밀 진단 해볼래요?" 바로가기 추가 — 질문에 답하고 성향 진단(페르소나 진단)으로 한 번에 이동',
    ],
    category: 'dashboard',
  },
  {
    id: '2026-07-05-dashboard-overhaul-v4',
    version: 'v4.0.0',
    date: '2026-07-05',
    title: '대시보드 대개편 — 협업 지문·그날 이야기·코딩 리듬 3분해 + 프롬프트 코칭 개선',
    summary: '대시보드를 정보 밀도와 읽는 흐름 기준으로 크게 재편했어요. AI 협업 지문·그날 이야기 같은 서사형 카드가 새로 들어오고, 코딩 리듬은 정보 하나당 칸 하나로 쪼갰습니다. 프롬프트 코칭도 더 정확하고 쉬운 말로 다듬었어요.',
    highlights: [
      'AI 협업 지문 카드 신설 — 본인 과거 기준선 대비 상승 신호를 분포형으로 (단정 대신 수치 + n= 표기)',
      '그날 이야기 카드 신설 — 단순 토큰 피크일 대신 "협업 서사 점수"가 가장 높은 날을 골라 보여줌',
      '코딩 리듬 카드를 3개로 분해 — 활동 밀도·요일 분포·시간대별을 각각 독립 칸으로',
      '신규 메트릭 2종 — 나 vs AI 글 비중(단어 수 기반), 모델 사용 강도',
      '활동 캘린더 압축 + 시간대별 활동 이동으로 상단 정보 흐름 정리',
      '프롬프트 코칭 정확도 수정 + 역상(과소평가) 칭찬 룰 추가 + 일반 사용자용 쉬운 말로 순화',
      '카드별 PNG 내보내기로 정리 (전체 화면 PNG 제거)',
    ],
    category: 'dashboard',
  },
  {
    id: '2026-05-17-qa-batch-ux-improvements',
    version: 'v3.6.2',
    date: '2026-05-17',
    title: 'QA 배치: 대화 기록 정렬 토글 + 새소식 팝오버 개선',
    summary: '대화 기록의 정렬 토글 기능을 추가하고, 새소식 팝오버 외부 클릭 닫기를 개선했어요. 성향 타입 배지의 시각 강도도 조정해 더 명확하게 표시돼요.',
    highlights: [
      '대화 기록 정렬 버튼 재클릭 시 오름/내림차순 토글 (날짜순/토큰 사용순 각각)',
      '정렬 방향을 화살표(↓/↑)로 시각화 — 현재 정렬 상태 한눈에',
      '다른 정렬 선택 시 기본값(내림차순)으로 초기화',
      '새소식 팝오버 외부 클릭 시 자동 닫기 (토글 버튼 제외해 의도치 않은 닫기 방지)',
      '성향 타입 배지(EWS 등) accent 색상 기반으로 강조 — 라벨과의 시각 위계 명확화',
      '오버레이 z-index 최적화로 스택 컨텍스트 정리',
    ],
    category: 'dashboard',
  },
  {
    id: '2026-05-08-replay-speed-and-host',
    version: 'v3.6.1',
    date: '2026-05-08',
    title: '리플레이 슬로우 옵션 + 같은 네트워크 다른 기기 접근',
    summary: '두 가지 사용자 피드백 반영. 리플레이가 너무 빨라 글이 화면 밖으로 흘러 읽기 어렵던 문제와, 휴대폰 같은 다른 기기에서 자기 PC의 memradar에 접근하고 싶다는 요청. 그리고 설치 없이 https://memradar.vercel.app 에서 .jsonl 파일 드래그&드롭으로 바로 사용도 가능합니다 — 모든 분석은 브라우저 안에서만 끝나고 외부로 전송되지 않아요.',
    highlights: [
      '리플레이 배속 슬로우 옵션 추가 — 0.25x · 0.5x · 1x · 2x · 5x (이전엔 1x · 2x · 5x)',
      '글자당 노출 시간 8ms → 30ms로 사람 친화적으로 재정의 — 1x가 사람 읽기 속도에 더 가까움',
      '긴 메시지 cap 4초 → 60초 — 긴 답변이 강제로 빠르게 압축되던 문제 해소',
      '자동 스크롤 영구 정지 — 사용자가 위로 올려 글 읽는 동안 화면이 빼앗기지 않음 (다시 바닥에 닿으면 재개)',
      '`memradar --server --host 0.0.0.0` — 같은 네트워크의 다른 기기(휴대폰·태블릿·다른 PC)에서 접근 가능. `MEMRADAR_HOST` 환경변수도 동일',
      '비-loopback 바인딩 시 LAN URL 자동 출력 + 보안 경고 — 공용 와이파이 등에서는 사용 금지',
      '웹사이트 https://memradar.vercel.app — 설치 없이 .jsonl 드래그&드롭, 데이터는 브라우저 안에만',
    ],
    category: 'workflow',
  },
  {
    id: '2026-05-08-session-export',
    version: 'v3.6.0',
    date: '2026-05-08',
    title: '세션 대화 HTML / Markdown 내보내기 + 전체·메시지 복사',
    summary: '세션 상세 화면에서 대화 전체를 HTML이나 마크다운 파일로 내보낼 수 있어요. 도구 호출 본문(Bash, Edit, Read 등)도 접힘 카드로 함께 들어가서 세션의 실제 흐름이 그대로 보존됩니다.',
    highlights: [
      '"내보내기" 드롭다운 — 채팅 화면 그대로 (HTML) / 단순 마크다운 HTML / 원본 마크다운 (.md) 3종 형식',
      '"전체 복사" — 대화 전체를 마크다운으로 클립보드 복사 (ChatGPT·메모장 등에 바로 붙여넣기)',
      '메시지 hover 시 메시지 단위 복사 버튼 — 한 메시지만 따로 복사',
      '도구 호출은 `<details>` 카드로 함께 export — 도구명 + 입력 + 결과까지, 기본 닫힘 상태라 길어도 깔끔',
      '서버 모드는 도구 본문까지 풍부하게, 정적 모드는 도구명만 chip 폴백',
      '모든 export 경로에서 시스템 태그·도구 메타 자동 정리 — 사람 대화로 깔끔하게',
    ],
    category: 'workflow',
  },
  {
    id: '2026-05-07-server-light-cache',
    version: 'v3.5.1',
    date: '2026-05-07',
    title: '서버 모드 거대 세션 환경 대응 (수천 세션 OK)',
    summary: '서버 모드(`--server`)가 수천 개 세션 환경에서도 즉시 응답해요. 기존엔 클라이언트가 세션마다 따로 받아 메모리 폭발이 났는데, 이제 서버가 한 번에 light parse 후 캐시해서 한 방에 보냅니다. GitHub 이슈 #2 제보 덕에 빠르게 확인하고 고쳤어요 — 알려주셔서 고맙습니다.',
    highlights: [
      '서버에서 light parse 결과 + 직렬화 JSON 까지 메모리 캐시 — 1500세션 응답 ~300ms (이전 시나리오는 브라우저가 멈춤)',
      '클라이언트는 `/api/light-sessions` 한 번 호출로 끝 — 메모리 사용 ~10x 감축',
      'Claude 메시지 본문 4000자 cap, 세션 클릭 시 풀 본문 lazy fetch',
      '자동 업데이트 무한 재시도 가드 — npx 캐시가 옛 버전이어도 재귀 spawn 안 됨',
      '정적 HTML 출력이 200MB 넘으면 서버 모드 권장 안내 + 자동 열기 생략',
      '제보: github.com/on1659/memradar/issues/2 — 알려주셔서 감사해요',
    ],
    category: 'workflow',
  },
  {
    id: '2026-05-06-tool-call-bodies',
    version: 'v3.5.0',
    date: '2026-05-06',
    title: '서버 모드에서 도구 호출 본문 표시',
    summary: '`memradar --server`로 띄운 세션 뷰에서 Edit·Bash·Write 같은 도구 호출의 본문이 카드로 펼쳐져요. Claude Code 터미널에서 보던 것과 비슷하게 diff·명령어·결과까지 한자리에서 확인할 수 있어요.',
    highlights: [
      'Edit / Write — 빨강(old) / 초록(new) 2단 diff + 라인 증감 통계',
      'Bash — 명령어 + 결과(stdout/stderr), 에러는 빨간 톤으로 강조',
      'Read / Grep / Glob — 결과 본문 표시',
      '카드 헤더 클릭으로 개별 접기/펼치기, 위쪽 "모두 접기/펼치기" 버튼으로 일괄 토글 (기본은 모두 접힘)',
      '긴 본문(KB 단위)은 "더 보기" 토글로 잘라 표시 — 메모리·스크롤 부담 최소화',
      '정적 HTML 모드는 기존 도구 이름 칩 그대로 — 단일 HTML 파일 용량 보호',
    ],
    category: 'workflow',
  },
  {
    id: '2026-05-05-large-sessions-streaming-write',
    version: 'v3.4.7',
    date: '2026-05-05',
    title: '대규모 세션 환경 실행 실패 수정',
    summary: '세션 수가 많은 환경에서 정적 HTML 빌드 중 RangeError로 실행이 멈추던 문제를 고쳤어요. 이제 수천 개 세션 환경에서도 정상적으로 출력돼요.',
    highlights: [
      '세션 직렬화를 스트리밍 방식으로 전환 — V8 문자열 길이 한계(~512MB) 회피',
      '거대 세션 환경에서 발생하던 "RangeError: Invalid string length" 차단',
    ],
    category: 'workflow',
  },
  {
    id: '2026-04-30-resume-hint-cleanup',
    version: 'v3.4.6',
    date: '2026-04-30',
    title: 'resume 안내 보조 문구 제거',
    summary: 'resume 명령 박스에서 줄바꿈으로 어색해 보이던 보조 문구를 정리했어요. 안내 문장이 한 줄로 깔끔하게 표시돼요.',
    highlights: [
      '"(복사 시 프로젝트 경로 이동 명령도 함께)" 보조 문구 삭제',
      'resume 박스 안내 한 줄 유지',
    ],
    category: 'workflow',
  },
  {
    id: '2026-04-30-cd-resume-combined-copy',
    version: 'v3.4.5',
    date: '2026-04-30',
    title: 'cd + resume 한 번에 복사',
    summary: '세션 뷰의 resume 명령 복사 버튼이 프로젝트 경로 이동(cd) 명령까지 함께 복사해요. 한 번 붙여넣기로 디렉토리 이동 + 세션 재개가 끝나요.',
    highlights: [
      'resume 복사 버튼: cd 명령 + claude/codex resume 합본 복사',
      'Windows 드라이브 전환(`D:`)도 cd 앞에 자동 포함',
      'cd 단독 복사 버튼은 그대로 유지',
    ],
    category: 'workflow',
  },
  {
    id: '2026-04-30-project-cd-copy',
    version: 'v3.4.4',
    date: '2026-04-30',
    title: '프로젝트 경로 cd 명령어 복사',
    summary: '세션 뷰 상단 프로젝트 경로 옆에 복사 버튼이 생겼어요. 드라이브 전환까지 포함된 cd 명령을 그대로 터미널에 붙여넣을 수 있어요.',
    highlights: [
      '세션 cwd 옆 cd 명령 복사 버튼 추가',
      'Windows: 드라이브 전환(`D:`) + `cd "..."` 두 줄 자동 구성',
      '그 외 OS: 단일 `cd "..."` 명령',
    ],
    category: 'workflow',
  },
  {
    id: '2026-04-26-server-reload-button',
    version: 'v3.4.3',
    date: '2026-04-26',
    title: '서버 모드 세션 새로 고침 버튼',
    summary: '서버 모드에서 새 세션 로그가 추가됐을 때 페이지 전체를 새로고치지 않고도 세션 데이터를 다시 불러올 수 있어요.',
    highlights: [
      '서버 모드 전용 세션 새로 고침 버튼 추가',
      '새 세션이 추가되거나 메시지가 늘어나면 한 번 클릭으로 반영',
    ],
    category: 'dashboard',
  },
  {
    id: '2026-04-26-codex-token-per-message',
    version: 'v3.4.2',
    date: '2026-04-26',
    title: 'Codex 메시지별 토큰 + Claude 유저 메시지 토큰 추정',
    summary: 'Codex 세션도 메시지별 토큰 델타가 표시되고, Claude 유저 메시지에도 토큰 수가 추정 표시돼요.',
    highlights: [
      'Codex 메시지별 토큰 델타 표시',
      'Claude 유저 메시지 토큰 추정 (출력 추정값 기반)',
    ],
    category: 'insight',
  },
  {
    id: '2026-04-26-token-tooltip-position',
    version: 'v3.4.1',
    date: '2026-04-26',
    title: '세션 헤더 토큰 툴팁 위치 수정',
    summary: '세션 헤더 토큰 배지 툴팁이 잘리던 문제를 수정했어요. 이제 배지 아래쪽에 정상 표시돼요.',
    highlights: [
      '토큰 배지 툴팁 위치를 위 → 아래(`top-full`)로 변경',
      '상단 클리핑 이슈 해소',
    ],
    category: 'dashboard',
  },
  {
    id: '2026-04-24-claude-resume-flag-fix',
    version: 'v3.2.1',
    date: '2026-04-24',
    title: 'claude --resume 플래그 하이픈 오타 수정',
    summary: '세션 뷰에서 안내하던 resume 명령어가 `claude -resume`(하이픈 1개)으로 잘못 표시되던 오타를 수정했어요. 이제 `claude --resume` 정상 표기.',
    highlights: [
      'SessionView resume 안내 문구 `-resume` → `--resume` 수정',
      '복사 후 그대로 붙여넣어도 정상 동작',
    ],
    category: 'workflow',
  },
  {
    id: '2026-04-26-codex-resume-copy',
    version: 'v3.4.0',
    date: '2026-04-26',
    title: 'Codex 세션 resume 명령어 복붙 지원',
    summary: 'Codex 세션 뷰에서도 `codex resume <id>` 명령어를 바로 복사할 수 있어요. Claude 세션과 동일하게 한 번 클릭으로 터미널에 붙여넣을 수 있습니다.',
    highlights: [
      'Codex 세션 뷰에 resume 명령어 복붙 버튼 추가',
      '"Claude에서는" 문구 → 세션 출처에 따라 자동 변경 (Claude / Codex)',
    ],
    category: 'workflow',
  },
  {
    id: '2026-04-26-token-cost-tooltip',
    version: 'v3.3.0',
    date: '2026-04-26',
    title: '토큰 비용 툴팁 + 캐시 요금 계산 수정',
    summary: '세션·메시지 토큰 뱃지에 마우스를 올리면 정확한 수치와 API 예상 비용이 표시돼요. 캐시 쓰기 요금 계산 오류도 수정됐어요.',
    highlights: [
      '세션 헤더 토큰 뱃지: hover 시 입력/출력/캐시 breakdown + 예상 비용',
      '메시지 토큰 뱃지: hover 시 정확한 수치(쉼표 형식) + 예상 비용',
      'cache_creation 토큰 요금 수정 ($0.30 → $3.75/M for Sonnet)',
      'claude-haiku-3.5/4+ 별도 요금 적용 ($0.80 input / $4 output)',
      '토큰 비용 툴팁 레이어 클리핑 버그 수정',
    ],
    category: 'dashboard',
  },
  {
    id: '2026-04-22-role-scoring-v3',
    version: 'v3.2.0',
    date: '2026-04-22',
    title: 'AI 역할 정확도 재설계 & 토큰 배지 정리',
    summary: 'AI가 수행한 역할을 더 정확하게 판별하도록 스코어링 로직을 재설계했어요. 히스토리·세션 뷰의 토큰 배지도 한 가지 스타일로 통일됐어요.',
    highlights: ['AI 역할 스코어링 Phase 1~3 재설계 (구조적 시그널·혼합 역할·신뢰도 지표)', '역할 시그널 어휘를 실전 사용 패턴 기반으로 재조정', '토큰 배지 UI 통일 (히스토리 / 세션 헤더 / 메시지)', '유저 메시지에도 토큰 수 표시 (초록 배지)', '메시지에 섞이던 <image> 태그 자동 정리', 'memtest 스킬 + AI 역할 평가 자동화 도입'],
    category: 'insight',
  },
  {
    id: '2026-04-20-session-replay',
    version: 'v3.1.4',
    date: '2026-04-20',
    title: '세션 리플레이 & AI 직업 라벨 리브랜딩',
    summary: '세션을 타임라인 스크러버로 되감기·재생할 수 있어요. AI 직업 카테고리 라벨도 더 친근한 표현으로 정돈됐어요.',
    highlights: ['세션 리플레이 프로토타입 (타임라인 스크러버)', 'AI 직업 카테고리 라벨 재정돈', '새소식 v3.0.1~v3.1.1 누락 내역 보강'],
    category: 'workflow',
  },
  {
    id: '2026-04-20-session-view-ux',
    version: 'v3.1.2',
    date: '2026-04-20',
    title: 'HTML 단일 파일 기본 모드 & 세션 뷰 개선',
    summary: 'npx memradar@latest 하나로 단일 HTML 파일이 생성돼 바로 열려요. 세션 뷰는 마크다운 렌더링과 말풍선 레이아웃으로 개선됐어요.',
    highlights: ['HTML 파일 생성이 기본 모드로 변경 (서버 불필요)', '세션 대화 마크다운 렌더링 지원', '배지 색상 테마별 자동 적용', 'npx 실행 시 구버전이면 자동으로 최신 버전 재실행'],
    category: 'workflow',
  },
  {
    id: '2026-04-19-npx-auto-reexec',
    version: 'v3.1.1',
    date: '2026-04-19',
    title: 'npx 실행 시 신버전 자동 재실행',
    summary: 'npx memradar@latest 실행 시 구버전이 캐시돼 있어도 최신 버전을 자동으로 감지해 바로 재실행돼요.',
    highlights: ['구버전 캐시 감지 후 최신 버전으로 자동 재실행', '업데이트 확인 없이 항상 최신 버전 실행 보장'],
    category: 'workflow',
  },
  {
    id: '2026-04-19-session-view-markdown',
    version: 'v3.1.0',
    date: '2026-04-19',
    title: '세션 뷰 마크다운 렌더링 & 배지 개선',
    summary: '세션 대화 내용이 마크다운으로 렌더링되고, 모델 배지 색상이 라이트/다크 테마에 따라 자동으로 조정돼요.',
    highlights: ['세션 메시지 마크다운 렌더링 (코드 블록, 표, 링크 등)', '모델 배지 색상 테마 인식형으로 변경 (에메랄드 그린)', '상단 버튼 레이아웃 서브타이틀 기준선 정렬'],
    category: 'dashboard',
  },
  {
    id: '2026-04-18-auto-update-spawn',
    version: 'v3.0.3',
    date: '2026-04-18',
    title: '업데이트 알림 정렬 수정',
    summary: '터미널에서 업데이트 알림 텍스트 정렬이 깨지던 문제를 수정했어요.',
    highlights: ['업데이트 안내 문구 정렬 오류 수정', 'CLI 출력 가독성 개선'],
    category: 'workflow',
  },
  {
    id: '2026-04-18-auto-update-prompt',
    version: 'v3.0.2',
    date: '2026-04-18',
    title: '자동 업데이트 설치 프롬프트',
    summary: '새 버전이 있을 때 확인하면 자동으로 최신 버전을 설치하고 재실행해요.',
    highlights: ['업데이트 확인 시 자동 설치 및 재실행', '사용자 확인 후 npx --yes로 최신 버전 실행'],
    category: 'workflow',
  },
  {
    id: '2026-04-18-update-notifier',
    version: 'v3.0.1',
    date: '2026-04-18',
    title: '업데이트 알림 기능',
    summary: '실행 시 새 버전이 배포돼 있으면 터미널에 업데이트 안내가 표시돼요.',
    highlights: ['npm 레지스트리에서 최신 버전 자동 확인', '새 버전 있을 때 업데이트 안내 출력'],
    category: 'workflow',
  },
  {
    id: '2026-04-18-session-donut',
    version: 'v3.0.0',
    date: '2026-04-18',
    title: '세션 길이 도넛 & 스킬 도넛 차트',
    summary: '세션 길이 분포와 자주 사용한 스킬(도구)을 도넛 차트로 한눈에 볼 수 있어요.',
    highlights: ['세션 길이 도넛 차트 추가 (Quick/Standard/Deep)', '스킬 사용 도넛 차트 추가', '탑바 레이아웃 위치 조정'],
    category: 'dashboard',
  },
  {
    id: '2026-04-18-personality-redesign',
    version: 'v0.2.12',
    date: '2026-04-18',
    title: '코딩 성격 유형 시스템 재설계',
    summary: 'AI 도구 사용량이 아닌 사용자의 실제 행동 패턴(메시지 스타일, 프로젝트 집중도, 세션 리듬)으로 성격 유형을 판별해요.',
    highlights: ['설계자/탐험가, 한우물/유목민, 마라토너/스프린터 3축', 'AI 직업 카테고리 통합 및 "내 AI의 직업" 리브랜딩', '세션 종류(Quick/Standard/Deep) 기반 리듬 분석'],
    category: 'insight',
  },
  {
    id: '2026-04-17-server-mode',
    version: 'v0.2.2',
    date: '2026-04-17',
    title: '로컬 서버 모드 전환',
    summary: 'npx memradar가 이제 로컬 서버를 띄워 앱을 즉시 로드해요. 18 MB HTML 대신 0.6 MB 앱이 바로 열리고, 세션은 백그라운드로 스트리밍돼요.',
    highlights: ['localhost:3939 서버 자동 기동', '세션 10개씩 점진 로딩', '기존 HTML 모드는 --static 플래그로 유지'],
    category: 'workflow',
  },
  {
    id: '2026-04-17-codex-support',
    version: 'v0.2.0',
    date: '2026-04-17',
    title: 'Codex 세션 지원',
    summary: 'Claude 세션과 함께 Codex 세션 로그도 자동으로 스캔하고 분석해요. 토큰 가격 계산과 테마 정책도 추가됐어요.',
    highlights: ['~/.codex/sessions/ 자동 스캔', '토큰 비용 계산 라이브러리', '테마 정책 모듈 추가'],
    category: 'insight',
  },
  {
    id: '2026-04-15-dashboard-polish',
    version: 'v0.1.4',
    date: '2026-04-15',
    title: '대시보드 폴리시',
    summary: '히트맵 비율, 카드 정렬, 툴팁 레이어를 다듬어 메인 화면이 더 안정적으로 보이게 정리했어요.',
    highlights: ['활동 히트맵 레이아웃 재정렬', '툴팁과 팝오버 레이어 정리', '세션 지표 카드 정렬 보정'],
    category: 'dashboard',
  },
  {
    id: '2026-04-15-theme-refresh',
    version: 'v0.1.3',
    date: '2026-04-15',
    title: '테마 선택 개선',
    summary: '시스템 다크/라이트 기본값을 따르도록 정리하고, 모드와 포인트 색을 다시 고르기 쉽게 바꿨어요.',
    highlights: ['시스템 테마 기본 연동', '포인트 색 선택 흐름 정리', '뒤로 가기 가능한 테마 패널'],
    category: 'theme',
  },
  {
    id: '2026-04-14-insight-updates',
    version: 'v0.1.2',
    date: '2026-04-14',
    title: '인사이트 상호작용 강화',
    summary: '시간대 그래프, 워드클라우드, 모델 그래프에서 hover 정보가 더 자연스럽게 보이도록 손봤어요.',
    highlights: ['시간대 툴팁 개선', '워드클라우드 hover 정보 추가', '모델 도넛 차트 오버레이 정리'],
    category: 'insight',
  },
  {
    id: '2026-04-13-workflow-release',
    version: 'v0.1.1',
    date: '2026-04-13',
    title: '탐색 플로우 확장',
    summary: '세션 검색, Code Report, 로컬 로그 자동 불러오기까지 연결해 첫 사용 흐름을 매끄럽게 만들었어요.',
    highlights: ['세션 검색 뷰 추가', 'Code Report 경험 확장', '로컬 로그 자동 로드'],
    category: 'workflow',
  },
]

export const latestProductUpdate = productUpdates[0]
