export interface ProductUpdate {
  id: string
  version: string
  date: string
  title: string
  summary: string
  highlights: string[]
  category: 'dashboard' | 'theme' | 'insight' | 'workflow'
}

export const productUpdates: ProductUpdate[] = [
  {
    id: '2026-05-07-server-light-cache',
    version: 'v3.5.1',
    date: '2026-05-07',
    title: '서버 모드 거대 세션 환경 대응 (수천 세션 OK)',
    summary: '서버 모드(`--server`)가 수천 개 세션 환경에서도 즉시 응답해요. 기존엔 클라이언트가 세션마다 따로 받아 메모리 폭발이 났는데, 이제 서버가 한 번에 light parse 후 캐시해서 한 방에 보냅니다.',
    highlights: [
      '서버에서 light parse 결과 + 직렬화 JSON 까지 메모리 캐시 — 1500세션 응답 ~300ms (이전 시나리오는 브라우저가 멈춤)',
      '클라이언트는 `/api/light-sessions` 한 번 호출로 끝 — 메모리 사용 ~10x 감축',
      'Claude 메시지 본문 4000자 cap, 세션 클릭 시 풀 본문 lazy fetch',
      '자동 업데이트 무한 재시도 가드 — npx 캐시가 옛 버전이어도 재귀 spawn 안 됨',
      '정적 HTML 출력이 200MB 넘으면 서버 모드 권장 안내 + 자동 열기 생략',
    ],
    category: 'workflow',
  },
  {
    id: '2026-05-06-tool-call-bodies',
    version: 'v3.5.0',
    date: '2026-05-06',
    title: '서버 모드에서 도구 호출 본문 표시',
    summary: '`memradar --server`로 띄운 세션 뷰에서 Edit·Bash·Write 같은 도구 호출의 본문이 카드로 펼쳐져요. Claude Code 터미널에서 보던 것과 비슷하게 diff·명령어·결과까지 한자리에서 확인할 수 있어요.',
    highlights: [
      'Edit / Write — 빨강(old) / 초록(new) 2단 diff + 라인 증감 통계',
      'Bash — 명령어 + 결과(stdout/stderr), 에러는 빨간 톤으로 강조',
      'Read / Grep / Glob — 결과 본문 표시',
      '카드 헤더 클릭으로 개별 접기/펼치기, 위쪽 "모두 접기/펼치기" 버튼으로 일괄 토글 (기본은 모두 접힘)',
      '긴 본문(KB 단위)은 "더 보기" 토글로 잘라 표시 — 메모리·스크롤 부담 최소화',
      '정적 HTML 모드는 기존 도구 이름 칩 그대로 — 단일 HTML 파일 용량 보호',
    ],
    category: 'workflow',
  },
  {
    id: '2026-05-05-large-sessions-streaming-write',
    version: 'v3.4.7',
    date: '2026-05-05',
    title: '대규모 세션 환경 실행 실패 수정',
    summary: '세션 수가 많은 환경에서 정적 HTML 빌드 중 RangeError로 실행이 멈추던 문제를 고쳤어요. 이제 수천 개 세션 환경에서도 정상적으로 출력돼요.',
    highlights: [
      '세션 직렬화를 스트리밍 방식으로 전환 — V8 문자열 길이 한계(~512MB) 회피',
      '거대 세션 환경에서 발생하던 "RangeError: Invalid string length" 차단',
    ],
    category: 'workflow',
  },
  {
    id: '2026-04-30-resume-hint-cleanup',
    version: 'v3.4.6',
    date: '2026-04-30',
    title: 'resume 안내 보조 문구 제거',
    summary: 'resume 명령 박스에서 줄바꿈으로 어색해 보이던 보조 문구를 정리했어요. 안내 문장이 한 줄로 깔끔하게 표시돼요.',
    highlights: [
      '"(복사 시 프로젝트 경로 이동 명령도 함께)" 보조 문구 삭제',
      'resume 박스 안내 한 줄 유지',
    ],
    category: 'workflow',
  },
  {
    id: '2026-04-30-cd-resume-combined-copy',
    version: 'v3.4.5',
    date: '2026-04-30',
    title: 'cd + resume 한 번에 복사',
    summary: '세션 뷰의 resume 명령 복사 버튼이 프로젝트 경로 이동(cd) 명령까지 함께 복사해요. 한 번 붙여넣기로 디렉토리 이동 + 세션 재개가 끝나요.',
    highlights: [
      'resume 복사 버튼: cd 명령 + claude/codex resume 합본 복사',
      'Windows 드라이브 전환(`D:`)도 cd 앞에 자동 포함',
      'cd 단독 복사 버튼은 그대로 유지',
    ],
    category: 'workflow',
  },
  {
    id: '2026-04-30-project-cd-copy',
    version: 'v3.4.4',
    date: '2026-04-30',
    title: '프로젝트 경로 cd 명령어 복사',
    summary: '세션 뷰 상단 프로젝트 경로 옆에 복사 버튼이 생겼어요. 드라이브 전환까지 포함된 cd 명령을 그대로 터미널에 붙여넣을 수 있어요.',
    highlights: [
      '세션 cwd 옆 cd 명령 복사 버튼 추가',
      'Windows: 드라이브 전환(`D:`) + `cd "..."` 두 줄 자동 구성',
      '그 외 OS: 단일 `cd "..."` 명령',
    ],
    category: 'workflow',
  },
  {
    id: '2026-04-26-server-reload-button',
    version: 'v3.4.3',
    date: '2026-04-26',
    title: '서버 모드 세션 새로 고침 버튼',
    summary: '서버 모드에서 새 세션 로그가 추가됐을 때 페이지 전체를 새로고치지 않고도 세션 데이터를 다시 불러올 수 있어요.',
    highlights: [
      '서버 모드 전용 세션 새로 고침 버튼 추가',
      '새 세션이 추가되거나 메시지가 늘어나면 한 번 클릭으로 반영',
    ],
    category: 'dashboard',
  },
  {
    id: '2026-04-26-codex-token-per-message',
    version: 'v3.4.2',
    date: '2026-04-26',
    title: 'Codex 메시지별 토큰 + Claude 유저 메시지 토큰 추정',
    summary: 'Codex 세션도 메시지별 토큰 델타가 표시되고, Claude 유저 메시지에도 토큰 수가 추정 표시돼요.',
    highlights: [
      'Codex 메시지별 토큰 델타 표시',
      'Claude 유저 메시지 토큰 추정 (출력 추정값 기반)',
    ],
    category: 'insight',
  },
  {
    id: '2026-04-26-token-tooltip-position',
    version: 'v3.4.1',
    date: '2026-04-26',
    title: '세션 헤더 토큰 툴팁 위치 수정',
    summary: '세션 헤더 토큰 배지 툴팁이 잘리던 문제를 수정했어요. 이제 배지 아래쪽에 정상 표시돼요.',
    highlights: [
      '토큰 배지 툴팁 위치를 위 → 아래(`top-full`)로 변경',
      '상단 클리핑 이슈 해소',
    ],
    category: 'dashboard',
  },
  {
    id: '2026-04-24-claude-resume-flag-fix',
    version: 'v3.2.1',
    date: '2026-04-24',
    title: 'claude --resume 플래그 하이픈 오타 수정',
    summary: '세션 뷰에서 안내하던 resume 명령어가 `claude -resume`(하이픈 1개)으로 잘못 표시되던 오타를 수정했어요. 이제 `claude --resume` 정상 표기.',
    highlights: [
      'SessionView resume 안내 문구 `-resume` → `--resume` 수정',
      '복사 후 그대로 붙여넣어도 정상 동작',
    ],
    category: 'workflow',
  },
  {
    id: '2026-04-26-codex-resume-copy',
    version: 'v3.4.0',
    date: '2026-04-26',
    title: 'Codex 세션 resume 명령어 복붙 지원',
    summary: 'Codex 세션 뷰에서도 `codex resume <id>` 명령어를 바로 복사할 수 있어요. Claude 세션과 동일하게 한 번 클릭으로 터미널에 붙여넣을 수 있습니다.',
    highlights: [
      'Codex 세션 뷰에 resume 명령어 복붙 버튼 추가',
      '"Claude에서는" 문구 → 세션 출처에 따라 자동 변경 (Claude / Codex)',
    ],
    category: 'workflow',
  },
  {
    id: '2026-04-26-token-cost-tooltip',
    version: 'v3.3.0',
    date: '2026-04-26',
    title: '토큰 비용 툴팁 + 캐시 요금 계산 수정',
    summary: '세션·메시지 토큰 뱃지에 마우스를 올리면 정확한 수치와 API 예상 비용이 표시돼요. 캐시 쓰기 요금 계산 오류도 수정됐어요.',
    highlights: [
      '세션 헤더 토큰 뱃지: hover 시 입력/출력/캐시 breakdown + 예상 비용',
      '메시지 토큰 뱃지: hover 시 정확한 수치(쉼표 형식) + 예상 비용',
      'cache_creation 토큰 요금 수정 ($0.30 → $3.75/M for Sonnet)',
      'claude-haiku-3.5/4+ 별도 요금 적용 ($0.80 input / $4 output)',
      '토큰 비용 툴팁 레이어 클리핑 버그 수정',
    ],
    category: 'dashboard',
  },
  {
    id: '2026-04-22-role-scoring-v3',
    version: 'v3.2.0',
    date: '2026-04-22',
    title: 'AI 역할 정확도 재설계 & 토큰 배지 정리',
    summary: 'AI가 수행한 역할을 더 정확하게 판별하도록 스코어링 로직을 재설계했어요. 히스토리·세션 뷰의 토큰 배지도 한 가지 스타일로 통일됐어요.',
    highlights: ['AI 역할 스코어링 Phase 1~3 재설계 (구조적 시그널·혼합 역할·신뢰도 지표)', '역할 시그널 어휘를 실전 사용 패턴 기반으로 재조정', '토큰 배지 UI 통일 (히스토리 / 세션 헤더 / 메시지)', '유저 메시지에도 토큰 수 표시 (초록 배지)', '메시지에 섞이던 <image> 태그 자동 정리', 'memtest 스킬 + AI 역할 평가 자동화 도입'],
    category: 'insight',
  },
  {
    id: '2026-04-20-session-replay',
    version: 'v3.1.4',
    date: '2026-04-20',
    title: '세션 리플레이 & AI 직업 라벨 리브랜딩',
    summary: '세션을 타임라인 스크러버로 되감기·재생할 수 있어요. AI 직업 카테고리 라벨도 더 친근한 표현으로 정돈됐어요.',
    highlights: ['세션 리플레이 프로토타입 (타임라인 스크러버)', 'AI 직업 카테고리 라벨 재정돈', '새소식 v3.0.1~v3.1.1 누락 내역 보강'],
    category: 'workflow',
  },
  {
    id: '2026-04-20-session-view-ux',
    version: 'v3.1.2',
    date: '2026-04-20',
    title: 'HTML 단일 파일 기본 모드 & 세션 뷰 개선',
    summary: 'npx memradar@latest 하나로 단일 HTML 파일이 생성돼 바로 열려요. 세션 뷰는 마크다운 렌더링과 말풍선 레이아웃으로 개선됐어요.',
    highlights: ['HTML 파일 생성이 기본 모드로 변경 (서버 불필요)', '세션 대화 마크다운 렌더링 지원', '배지 색상 테마별 자동 적용', 'npx 실행 시 구버전이면 자동으로 최신 버전 재실행'],
    category: 'workflow',
  },
  {
    id: '2026-04-19-npx-auto-reexec',
    version: 'v3.1.1',
    date: '2026-04-19',
    title: 'npx 실행 시 신버전 자동 재실행',
    summary: 'npx memradar@latest 실행 시 구버전이 캐시돼 있어도 최신 버전을 자동으로 감지해 바로 재실행돼요.',
    highlights: ['구버전 캐시 감지 후 최신 버전으로 자동 재실행', '업데이트 확인 없이 항상 최신 버전 실행 보장'],
    category: 'workflow',
  },
  {
    id: '2026-04-19-session-view-markdown',
    version: 'v3.1.0',
    date: '2026-04-19',
    title: '세션 뷰 마크다운 렌더링 & 배지 개선',
    summary: '세션 대화 내용이 마크다운으로 렌더링되고, 모델 배지 색상이 라이트/다크 테마에 따라 자동으로 조정돼요.',
    highlights: ['세션 메시지 마크다운 렌더링 (코드 블록, 표, 링크 등)', '모델 배지 색상 테마 인식형으로 변경 (에메랄드 그린)', '상단 버튼 레이아웃 서브타이틀 기준선 정렬'],
    category: 'dashboard',
  },
  {
    id: '2026-04-18-auto-update-spawn',
    version: 'v3.0.3',
    date: '2026-04-18',
    title: '업데이트 알림 정렬 수정',
    summary: '터미널에서 업데이트 알림 텍스트 정렬이 깨지던 문제를 수정했어요.',
    highlights: ['업데이트 안내 문구 정렬 오류 수정', 'CLI 출력 가독성 개선'],
    category: 'workflow',
  },
  {
    id: '2026-04-18-auto-update-prompt',
    version: 'v3.0.2',
    date: '2026-04-18',
    title: '자동 업데이트 설치 프롬프트',
    summary: '새 버전이 있을 때 확인하면 자동으로 최신 버전을 설치하고 재실행해요.',
    highlights: ['업데이트 확인 시 자동 설치 및 재실행', '사용자 확인 후 npx --yes로 최신 버전 실행'],
    category: 'workflow',
  },
  {
    id: '2026-04-18-update-notifier',
    version: 'v3.0.1',
    date: '2026-04-18',
    title: '업데이트 알림 기능',
    summary: '실행 시 새 버전이 배포돼 있으면 터미널에 업데이트 안내가 표시돼요.',
    highlights: ['npm 레지스트리에서 최신 버전 자동 확인', '새 버전 있을 때 업데이트 안내 출력'],
    category: 'workflow',
  },
  {
    id: '2026-04-18-session-donut',
    version: 'v3.0.0',
    date: '2026-04-18',
    title: '세션 길이 도넛 & 스킬 도넛 차트',
    summary: '세션 길이 분포와 자주 사용한 스킬(도구)을 도넛 차트로 한눈에 볼 수 있어요.',
    highlights: ['세션 길이 도넛 차트 추가 (Quick/Standard/Deep)', '스킬 사용 도넛 차트 추가', '탑바 레이아웃 위치 조정'],
    category: 'dashboard',
  },
  {
    id: '2026-04-18-personality-redesign',
    version: 'v0.2.12',
    date: '2026-04-18',
    title: '코딩 성격 유형 시스템 재설계',
    summary: 'AI 도구 사용량이 아닌 사용자의 실제 행동 패턴(메시지 스타일, 프로젝트 집중도, 세션 리듬)으로 성격 유형을 판별해요.',
    highlights: ['설계자/탐험가, 한우물/유목민, 마라토너/스프린터 3축', 'AI 직업 카테고리 통합 및 "내 AI의 직업" 리브랜딩', '세션 종류(Quick/Standard/Deep) 기반 리듬 분석'],
    category: 'insight',
  },
  {
    id: '2026-04-17-server-mode',
    version: 'v0.2.2',
    date: '2026-04-17',
    title: '로컬 서버 모드 전환',
    summary: 'npx memradar가 이제 로컬 서버를 띄워 앱을 즉시 로드해요. 18 MB HTML 대신 0.6 MB 앱이 바로 열리고, 세션은 백그라운드로 스트리밍돼요.',
    highlights: ['localhost:3939 서버 자동 기동', '세션 10개씩 점진 로딩', '기존 HTML 모드는 --static 플래그로 유지'],
    category: 'workflow',
  },
  {
    id: '2026-04-17-codex-support',
    version: 'v0.2.0',
    date: '2026-04-17',
    title: 'Codex 세션 지원',
    summary: 'Claude 세션과 함께 Codex 세션 로그도 자동으로 스캔하고 분석해요. 토큰 가격 계산과 테마 정책도 추가됐어요.',
    highlights: ['~/.codex/sessions/ 자동 스캔', '토큰 비용 계산 라이브러리', '테마 정책 모듈 추가'],
    category: 'insight',
  },
  {
    id: '2026-04-15-dashboard-polish',
    version: 'v0.1.4',
    date: '2026-04-15',
    title: '대시보드 폴리시',
    summary: '히트맵 비율, 카드 정렬, 툴팁 레이어를 다듬어 메인 화면이 더 안정적으로 보이게 정리했어요.',
    highlights: ['활동 히트맵 레이아웃 재정렬', '툴팁과 팝오버 레이어 정리', '세션 지표 카드 정렬 보정'],
    category: 'dashboard',
  },
  {
    id: '2026-04-15-theme-refresh',
    version: 'v0.1.3',
    date: '2026-04-15',
    title: '테마 선택 개선',
    summary: '시스템 다크/라이트 기본값을 따르도록 정리하고, 모드와 포인트 색을 다시 고르기 쉽게 바꿨어요.',
    highlights: ['시스템 테마 기본 연동', '포인트 색 선택 흐름 정리', '뒤로 가기 가능한 테마 패널'],
    category: 'theme',
  },
  {
    id: '2026-04-14-insight-updates',
    version: 'v0.1.2',
    date: '2026-04-14',
    title: '인사이트 상호작용 강화',
    summary: '시간대 그래프, 워드클라우드, 모델 그래프에서 hover 정보가 더 자연스럽게 보이도록 손봤어요.',
    highlights: ['시간대 툴팁 개선', '워드클라우드 hover 정보 추가', '모델 도넛 차트 오버레이 정리'],
    category: 'insight',
  },
  {
    id: '2026-04-13-workflow-release',
    version: 'v0.1.1',
    date: '2026-04-13',
    title: '탐색 플로우 확장',
    summary: '세션 검색, Code Report, 로컬 로그 자동 불러오기까지 연결해 첫 사용 흐름을 매끄럽게 만들었어요.',
    highlights: ['세션 검색 뷰 추가', 'Code Report 경험 확장', '로컬 로그 자동 로드'],
    category: 'workflow',
  },
]

export const latestProductUpdate = productUpdates[0]
